/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheckBox: typeof import('./src/components/CheckBox/index.vue')['default']
    CodeInput: typeof import('./src/components/code-input/index.vue')['default']
    CustomerCom: typeof import('./src/components/customerCom/index.vue')['default']
    Detail: typeof import('./src/components/customerCom/detail.vue')['default']
    FileAddress: typeof import('./src/components/rxkForm/components/fileAddress.vue')['default']
    Filed: typeof import('./src/components/rxkForm/components/filed.vue')['default']
    FileDateCom: typeof import('./src/components/rxkForm/components/fileDateCom.vue')['default']
    FiledCheck: typeof import('./src/components/rxkForm/components/filedCheck.vue')['default']
    FiledIdcard: typeof import('./src/components/rxkForm/components/filedIdcard.vue')['default']
    FiledRadio: typeof import('./src/components/rxkForm/components/filedRadio.vue')['default']
    FiledUpload: typeof import('./src/components/rxkForm/components/filedUpload.vue')['default']
    FiledUploadFile: typeof import('./src/components/rxkForm/components/filedUploadFile.vue')['default']
    FileSelect: typeof import('./src/components/rxkForm/components/fileSelect.vue')['default']
    FileTimeCom: typeof import('./src/components/rxkForm/components/fileTimeCom.vue')['default']
    Page: typeof import('./src/components/customerCom/page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RxkForm: typeof import('./src/components/rxkForm/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VanArea: typeof import('vant/es')['Area']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
